### ISSUE TITLE
Queries about the approach

### ISSUE THREAD

**Issue by vikram-gupta** [minhnguyen-cs/mtsne#1]
Hi @minhnguyen-cs ,

Thanks for sharing this code. I read the paper and am a little confused about few points. It would be great if you can help me in understanding the following points.

1) The ATOM-HP dataset experiment looks like a case of normal clustering and not time series since you are treating all the points independently of time dimension. Is this understanding correct?

2) What is the intuition behind m-TSNE working better than a DTW based approach. Do you think m-TSNE which uses EROS distance AND warping would work better since warping is important in time-series?

Thanks

**Comment by minhnguyen-cs** [comment]
Hi @vikram-gupta ,

Sorry for this late response (somehow I did not receive notification for your posted question).

For your question, please find my answer below:

> 1. The ATOM-HP dataset experiment looks like a case of normal clustering and not time series since you are treating all the points independently of time dimension. Is this understanding correct?

Each point was actually a subsequence of a multivariate time-series (MTS). The experiment was to find subsequence of high-dimensional MTS that has similar patterns and to find anomaly (the time duration that involve different pattern). So hence, intuitively, you can say it was a clustering of MTS subsequences - not clustering of time points indepently. We also have an interactive UI with color marking in m-TSNE which I did not include in the paper to see the timely order of points in the visualization to help better understanding the time trend.

> 2. What is the intuition behind m-TSNE working better than a DTW based approach. Do you think m-TSNE which uses EROS distance AND warping would work better since warping is important in time-series?

The intuition with EROS was that it consider the correlation between MTS variables which is important in MTS. I would say DTW also works, but you have to have some methods to perform DTW on MTS. In the paper, we tried some methods which have been previously used in other related work like: concatenating univariate time series (MTS variables), then perform m-TSNE on the concatenated one, or just to perform DTW on pairs of MTS variables, etc. However, the result was shown not easily-interpreted based on the user survey, also note that when you combine univariate time series, you did not consider the correlation between MTS variables. If you have any idea of improving DTW for MTS in m-TSNE, I would love to talk to.

Combining EROS and warping is potentially an improvement for m-TSNE. In our work, for the experiment, we intentionally only did aligning the time of time series using date between patients because the patients have the similar chemotherapy treatment cycles, so we did not perform warping as to consider the relation between subsequences of MTS and the dates that patients received treatment, prescription, etc.

Please let me know if you have any question. Also, please do not hesitate to contact me via email: minhnngu@usc.edu

Thank you for your inquiries.
Minh
